# Go to dir with project in terminal and run:
#	c++ -MM *.cpp >> makefile

# Compile with debug option and all warnings on. ------------
CXX = c++
CXXFLAGS = -std=c++14 -g -Wall -O1

# Object modules comprising this application ----------------
OBJ-BATTLE-GAME = main.o battle.o

# Build targets
TARGETS = battle-game-exe

# .PHONY: means that the targets that follow should be built even
# though the are not real files.
.PHONY: clean
# all: $(TARGETS)

battle-game-exe: $(OBJ-BATTLE-GAME)
	$(CXX)  -o $@ $(CXXFLAGS) $(OBJ-BATTLE-GAME)

# Delete .o and exe files and force recompilation. ----------
clean:
	rm -f $(OBJ-BATTLE-GAME) $(TARGETS)

# Dependencies ----------------------------------------------
# The  lines below were generated by the c++ -MM command up at the top.
Battle.o: Battle.cpp Battle.hpp Actor.hpp GhostActor.hpp KnightActor.hpp \
  ActorFactory.hpp CommandManager.hpp Stack.hpp UndoableCommand.hpp \
  BattleMove.hpp BattleMoveFactory.hpp Attacks.hpp Utils.hpp
main.o: main.cpp Game.hpp Battle.hpp Actor.hpp GhostActor.hpp \
  KnightActor.hpp ActorFactory.hpp CommandManager.hpp Stack.hpp \
  UndoableCommand.hpp BattleMove.hpp BattleMoveFactory.hpp Attacks.hpp \
  Utils.hpp
